name: example
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  injectable:
    path: ../injectable/
  # auto_route:
  cupertino_icons: ^0.1.3
  dio:
  shared_preferences:
  firebase_auth: ^0.15.4
  get_it:

dev_dependencies:
  build_runner:
  build:
  # auto_route_generator:
  flutter_test:
    sdk: flutter
  injectable_generator:
    path: ../injectable_generator

flutter:
  uses-material-design: true
