name: example
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get_it: 5.0.0
  mockito: ^4.1.1
  injectable:
    # 1.0.3
    path: ../injectable

dev_dependencies:
  pedantic: ^1.8.0
  build_runner:
  effective_dart: ^1.2.0
  injectable_generator:
    #  1.0.3
    path: ../injectable_generator
