name: example
description: A simple command-line application.

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  get_it:  ">=6.0.0 <7.0.0"

dev_dependencies:
  pedantic: ^1.10.0
  build_runner: 1.11.5
  effective_dart: ^1.3.0
  injectable_generator:
    path: ../../injectable_generator
