name: example
description: A simple command-line application.

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  get_it:  ">=7.0.0 <8.0.0"

dev_dependencies:
  pedantic: ^1.11.1
  build_runner: ^2.1.1
  effective_dart: ^1.3.2
  injectable_generator:
    path: ../../injectable_generator
