name: example
description: A simple command-line application.
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  get_it:  ">=7.0.0 <9.0.0"
  injectable:


dev_dependencies:
  pedantic: ^1.11.1
  build_runner: ^2.4.14
  effective_dart: ^1.3.2
  lints: ^6.0.0
  injectable_generator:
