name: example
description: A simple command-line application.

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  get_it:  ">=8.3.0 <10.0.0"
  injectable: ^2.7.1+3
#    path: ../../injectable


dev_dependencies:
  pedantic: ^1.11.1
  build_runner: ^2.10.4
  lean_builder: ^0.1.6
  effective_dart: ^1.3.2
  lints: ^6.0.0
  injectable_generator: ^2.12.0
#    path: ../../injectable_generator
