name: example
description: A simple command-line application.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  get_it:  ">=7.0.0 <8.0.0"
  injectable:
    path: ../../injectable


dev_dependencies:
  pedantic: ^1.11.1
  build_runner: ^2.4.0
  effective_dart: ^1.3.2
  lints: ^2.1.0
  injectable_generator:
    path: ../../injectable_generator
