name: b
description: "Provides either mock or real implementation of the api"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  a:
    path: ../a
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  injectable:
    path: ../../../injectable
  logger: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.4
  injectable_generator:
    path: ../../../injectable_generator
  lints: ^5.1.1
