name: injectable
description: Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
version: 2.1.0
homepage: https://github.com/Milad-Akarie/injectable

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  get_it: ">=7.2.0 <8.0.0"

dev_dependencies:
  lints: ^2.0.0
