name: injectable
description: Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
version: 2.4.0
homepage: https://github.com/Milad-Akarie/injectable

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  get_it: ">=7.2.0 <8.0.0"
  meta: ^1.12.0

dev_dependencies:
  lints: ^3.0.0
