name: injectable
description: Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
version: 1.1.0
homepage: https://github.com/Milad-Akarie/injectable

environment:
  sdk: ">=2.12.0-259.12.beta <3.0.0"

dependencies:
  get_it: ">=6.0.0 <7.0.0"

dev_dependencies:
  pedantic: ^1.9.0