name: injectable
description: Injectable is a convenient code generator for [get_it](https://pub.dev/packages/get_it). Inspired by Angular DI, Guice DI and inject.dart.
version: 0.4.0
homepage: https://github.com/Milad-Akarie/injectable

environment:
  sdk: ">=2.5.0 <3.0.0"

