name: injectable
description: Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
version: 2.5.2
homepage: https://github.com/Milad-Akarie/injectable

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  get_it: ">=7.2.0 <9.0.0"
  meta: ^1.12.0

dev_dependencies:
  lints: ^6.0.0
