name: injectable_generator
description: Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
version: 2.3.0
homepage: https://github.com/Milad-Akarie/injectable

environment:
  sdk: ">=3.0.0<4.0.0"

dependencies:
  build: ^2.1.0
  source_gen: ^1.2.7
  path: ^1.8.0
  glob: ^2.0.1
  analyzer: ">=5.8.0 <7.0.0"
  code_builder: ^4.4.0
  dart_style: ^2.0.3
  injectable: ^2.2.0
#    path: ../injectable
  collection: ^1.18.0
  recase: ^4.1.0
  meta: ^1.9.1
dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.1.3
  test: ^1.17.12
  lints: ^2.0.0
