name: injectable_generator
description: Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
version: 2.11.0
homepage: https://github.com/Milad-Akarie/injectable

environment:
  sdk: ">=3.8.0<4.0.0"

dependencies:
  build: ^4.0.3
  source_gen: ^4.1.1
  path: ^1.9.0
  glob: ^2.1.3
  analyzer: ">=9.0.0 <10.0.0"
  code_builder: ^4.11.0
  dart_style: ^3.1.3
  injectable: #^2.7.0
      path: ../injectable
  collection: ^1.18.0
  recase: ^4.1.0
  meta: ^1.16.0
dev_dependencies:
  build_runner: ^2.10.4
  build_test: ^3.5.4
  test: ^1.28.0
  lints: ^6.0.0
