name: injectable_generator
description: Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
version: 1.5.4
homepage: https://github.com/Milad-Akarie/injectable

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.3.0
  source_gen: ^1.2.2
  path: ^1.8.2
  glob: ^2.1.0
  analyzer: ^4.2.0
  code_builder: ^4.1.0
  dart_style: ^2.2.3
  injectable:
       ^1.5.3
#     path: ../injectable
  collection: ^1.16.0
dev_dependencies:
  build_runner: ^2.2.0
  build_test: ^2.1.5
  test: ^1.21.4
