name: injectable_generator
description: Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
version: 1.2.2
homepage: https://github.com/Milad-Akarie/injectable

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.0.0
  source_gen: ^1.0.0
  path: ^1.8.0
  glob: ^2.0.0
  analyzer: ^1.2.0
  code_builder: ^3.7.0
  dart_style: ^2.0.0
  injectable: ^1.2.2
#     path: ../injectable
  collection: ^1.15.0
dev_dependencies:
  build_runner: ^1.12.2
  build_test: ^2.0.0
  test: ^1.16.8
