name: injectable_generator
description: Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
version: 1.0.7
homepage: https://github.com/Milad-Akarie/injectable

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.0.0
  source_gen: ^0.9.0
  path: ^1.6.0
  glob: ^1.1.7
  analyzer: ^0.40.1
  injectable: ^1.0.7
#     path: ../injectable
  collection: ^1.14.8
dev_dependencies:
  build_runner: ^1.0.0
  build_test:
  mockito:
  test:
