name: injectable_generator
description: Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
version: 1.2.0
homepage: https://github.com/Milad-Akarie/injectable

environment:
  sdk: ">=2.12.0-259.12.beta <3.0.0"

dependencies:
  build: ^1.6.3
  source_gen: ^0.9.10+3
  path: ^1.8.0
  glob: ^2.0.0
  analyzer: ^1.0.0
  code_builder: ^3.6.0
  dart_style: ^1.3.13
  injectable:
#    ^1.1.0
     path: ../injectable
  collection: ^1.15.0
dev_dependencies:
  build_runner: ^1.11.5
  build_test: ^1.3.7
  mockito:
  test: ^1.16.3
