name: injectable_generator
description: Injectable is a convenient code generator for [get_it](https://pub.dev/packages/get_it). Inspired by Angular DI, Guice DI and inject.dart.
version: 0.3.1
homepage: https://github.com/Milad-Akarie/injectable

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  build: ^1.0.0
  source_gen: ^0.9.0
  glob: ^1.1.7
  analyzer: ">=0.39.2 <0.40.0"

  injectable:
    ^0.3.0
    # path: ../injectable

dev_dependencies:
  build_runner: ^1.0.0
