name: Coverage
on:
  push:
    branches:
      - master
    paths:
      - 'injectable/lib/**'
      - 'injectable/test/**'
      - 'injectable/pubspec.yaml'
      - 'injectable_generator/lib/**'
      - 'injectable_generator/test/**'
      - 'injectable_generator/pubspec.yaml'
      - '.github/workflows/coverage.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'injectable/lib/**'
      - 'injectable/test/**'
      - 'injectable/pubspec.yaml'
      - 'injectable_generator/lib/**'
      - 'injectable_generator/test/**'
      - 'injectable_generator/pubspec.yaml'
      - '.github/workflows/coverage.yml'

jobs:
  coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: [injectable, injectable_generator]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Remove example directories
        run: |
          rm -rf injectable/example

      - name: Install dependencies
        working-directory: ${{ matrix.package }}
        run: dart pub get

      - name: Run tests with coverage
        working-directory: ${{ matrix.package }}
        run: dart run coverage:test_with_coverage

      - name: Format coverage
        working-directory: ${{ matrix.package }}
        run: |
          dart run coverage:format_coverage \
            --lcov \
            --in=coverage \
            --out=coverage/lcov.info \
            --packages=.dart_tool/package_config.json \
            --report-on=lib

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./${{ matrix.package }}/coverage/lcov.info
          flags: ${{ matrix.package }}
          name: ${{ matrix.package }}-coverage
          fail_ci_if_error: true
          verbose: true

